### ISSUE TITLE
"Save" click doesn't respect disabled

### ISSUE THREAD

**Issue by bryfox** [codaco/integration-tests#7]
The protocol creation test should actually be failing now, since we [require stages to be defined before saving](https://github.com/codaco/Architect/pull/241). In the test script, the ["Save" click](https://github.com/codaco/integration-tests/blob/master/test/create-protocol.test.js#L46) still works even though the enclosing button is disabled.

**Comment by wwqrd** [comment]
This test looks like it would pass to me as the protocol gets created on the filesystem when the user clicks 'create' in the file dialog. It is then opened for editing.

We may want to rethink this? Though I feel like "no stages" isn't a hard fail thing, and more of a nudge the user situation?

**Comment by bryfox** [comment]
You're right; the `existsSync` expectation could be moved near the top of the test. I'd expect the test to fail at the point of clicking, though. The `'.scene__home'` click fails since it's not visibly clickable; the `recentlyCreated` expectation (if it were reached) would fail if home isn't clicked.

Aside from the `existsSync`, do you think the test is OK as-is, then? I really just wanted something that exercised a basic editing flow and saved changes.

**Comment by wwqrd** [comment]
Now that I think about it, the home button probably should warn you if there are unsaved changes!

It isn't clear in the webdriver docs that clicking a disabled button should throw an error? A successful save click will hide the save button, so perhaps that should be the test for a successful click save?

**Comment by bryfox** [comment]
Sorry, to clarify: I don't think clicking a disabled button should throw the error. But the following action ('click .scene__home') should throw if '.scene_home' is not yet visible (which it shouldn't be since the "save" click should not have succeeded). Even if it that didn't throw, the first expect should fail.

> A successful save click will hide the save button, so perhaps that should be the test for a successful click save

Yeah, we could remove a couple of steps from the test and leave it at that. We'll still have the issue above, though; the 'save' click succeeds when it shouldn't.

This might just be a matter of the synthetic bubbling. The driver is actually clicking the span; I did that since the selector was much clearer. Putting the click directly on the button might work as expected.

**Comment by bryfox** [comment]
Sorry, you're right, of course — I thought I'd observed different behavior. Everything after the "save" click proceeds even if that click is removed.

I think the ‘bar hidden’ test is good; that’s really the state that represents a successful save as you pointed out.

**Comment by bryfox** [comment]
I think this was fixed with #8, but if you think we should make other changes, feel free to re-open.
